url: "https://lindsaykerr.gihub.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/webgl-playground" # the subpath of your site, e.g. /blog
title: "WebGL Playground" # the name of your site, e.g. ACME Corp.
